CREATE DATABASE library_management;

CREATE TABLE USERS(USER_ID SERIAL PRIMARY KEY NOT NULL, USER_NAME VARCHAR(50) NOT NULL UNIQUE);

CREATE TABLE BOOKS (BOOK_ID INT PRIMARY KEY NOT NULL, BOOK_TITLE VARCHAR(50) NOT NULL, BOOK_AUTHOR VARCHAR(50) NOT NULL, IS_AVAILABLE BOOLEAN);

CREATE TABLE LOANS (LOAN_ID SERIAL PRIMARY KEY NOT NULL, LOAN_BOOKTITLE VARCHAR(50) NOT NULL, BORROWER_NAME VARCHAR(50) NOT NULL,LOAN_BOOKID INT NOT NULL, FOREIGN KEY (LOAN_BOOKID) REFERENCES BOOKS(BOOK_ID), FOREIGN KEY (BORROWER_NAME) REFERENCES USERS(USER_NAME));

<!--insert of Data on table BOOKS>
INSERT INTO BOOKS VALUES (1,'Java Basics', 'Author A', TRUE), (2,'Advanced Java', 'Author B', TRUE), (3,'OOP Concepts', 'Author C', TRUE), (4,'Data Structures', 'Author D', TRUE), (5,'Algorithms', 'Author E', TRUE);